---
apiVersion: v2
name: node-local-dns
version: 1.4.0-rc.4
appVersion: 1.22.24
home: https://github.com/lablabs/k8s-nodelocaldns-helm
description: NodeLocal DNS Cache helm chart
keywords:
  - node
  - dns
  - cache
  - kubernetes
sources:
  - https://github.com/kubernetes/kubernetes/tree/master/cluster/addons/dns/nodelocaldns
maintainers:
  - name: martinhaus
  - name: haad
engine: gotpl
type: application
annotations:
  artifacthub.io/changes: |
    - Initial helm chart changelog
    - Update node-cache version, add support for better granular logging.
